"""     Introduccion a Excepciones     """

try:
    N1 = int(input("Ingrese primer n√∫mero: "))
except ValueError:
    print("Ocurrio un error")
